# Predict the selling price of the products

### Importing libraries

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Data preprocessing

In [47]:
df=pd.read_csv("./train.csv")
test=pd.read_csv("./test.csv")

In [48]:
df1=df.drop(["Product_id","instock_date","Customer_name"],axis="columns")

In [49]:
df1.head()

Stall_no  Market_Category Loyalty_customer Product_Category  Grade  Demand  \
0      37.0                2              Yes          Fashion      1      68   
1      38.0               24              Yes          Fashion      0      51   
2       9.0              447              Yes       Child_care      0      10   
3      50.0               23              Yes      Educational      2      48   
4       7.0               63              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2  Minimum_price  Maximum_price  \
0             0.0      376.0       11.0         2983.0         4713.0   
1             0.0      397.0       12.0         7495.0        10352.0   
2             0.0      250.0        9.0         5752.0         7309.0   
3             0.0      144.0       13.0         5090.0        20814.0   
4             1.0      211.0        4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917820  
4     906.553935

### Label encoding categorical data

In [50]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
le1=LabelEncoder()

df1.Loyalty_customer=le.fit_transform(df1.Loyalty_customer)
df1.Product_Category=le1.fit_transform(df1.Product_Category)

In [51]:
df1.isnull().sum()

Stall_no              5
Market_Category       0
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2           205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

df1.Stall_no           = df1.Stall_no.fillna(df1.Stall_no.mean())
df1.Discount_avail     = df1.Discount_avail.fillna(df1.Discount_avail.mean())
df1.charges_1          = df1.charges_1.fillna(df1.charges_1.mean())
df1.charges_2          = df1.charges_2.fillna(df1.charges_2.mean())
df1.Minimum_price      = df1.Minimum_price.fillna(df1.Minimum_price.mean())
df1.Maximum_price      = df1.Maximum_price.fillna(df1.Maximum_price.mean())
df1.Selling_Price      = df1.Selling_Price.fillna(df1.Selling_Price.mean())

In [52]:
df1=df1.dropna()

In [53]:
df1.shape

(5570, 12)

In [54]:
X=df1.iloc[:,:-1].values
y=df1.iloc[:,-1].values
X,y

(array([[3.7000e+01, 2.0000e+00, 1.0000e+00, ..., 1.1000e+01, 2.9830e+03,
         4.7130e+03],
        [3.8000e+01, 2.4000e+01, 1.0000e+00, ..., 1.2000e+01, 7.4950e+03,
         1.0352e+04],
        [9.0000e+00, 4.4700e+02, 1.0000e+00, ..., 9.0000e+00, 5.7520e+03,
         7.3090e+03],
        ...,
        [3.6000e+01, 3.5800e+02, 0.0000e+00, ..., 3.0000e+00, 5.3030e+03,
         1.4614e+04],
        [2.7000e+01, 4.5200e+02, 1.0000e+00, ..., 3.0000e+00, 4.3340e+03,
         5.8490e+03],
        [1.1000e+01, 5.8000e+01, 1.0000e+00, ..., 7.0000e+00, 3.9750e+03,
         5.3830e+03]]),
 array([ 4185.9477  ,  9271.490256,  6785.701362, ..., 10218.87878 ,
         5359.493997,  5220.013568]))

In [55]:
from sklearn.preprocessing import MinMaxScaler
x_scaler = MinMaxScaler()
y_scaler = MinMaxScaler()
y=y.reshape(len(y),1)
X=x_scaler.fit_transform(X)
y=y_scaler.fit_transform(y)

### Random forest model

In [56]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

ran_reg=RandomForestRegressor()
svr_reg=SVR()

In [57]:
ran_reg.fit(X,y)


<ipython-input-57-27445adbfbb9>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  ran_reg.fit(X,y)


RandomForestRegressor()

In [58]:
svr_reg.fit(X,y)

C:\Users\Welcome\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [59]:
test
testsvr=test.copy()

In [60]:
test.isnull().sum()

Product_id           0
Stall_no             1
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2            5
Minimum_price       14
Maximum_price        0
dtype: int64

In [61]:
test1=test.copy()

In [62]:
test1=test.drop(["Product_id","instock_date","Customer_name"],axis="columns")

In [63]:
le3=LabelEncoder()
le4=LabelEncoder()
test1.Loyalty_customer=le3.fit_transform(test1.Loyalty_customer)
test1.Product_Category=le4.fit_transform(test1.Product_Category)

In [64]:
test1.Stall_no=test.Stall_no.fillna(test1.Stall_no.mean())
test1.charges_1=test1.charges_1.fillna(test1.charges_1.mean())
test1.charges_2=test1.charges_2.fillna(test1.charges_2.mean())
test1.Minimum_price=test1.Minimum_price.fillna(test1.Minimum_price.mean())

In [65]:
test1.head()

Stall_no  Market_Category  Loyalty_customer  Product_Category  Grade  \
0      39.0              205                 0                 3      0   
1      49.0                3                 1                 3      0   
2       1.0              183                 0                 9      2   
3       8.0              358                 1                 0      3   
4      33.0              167                 0                 9      0   

   Demand  Discount_avail  charges_1  charges_2  Minimum_price  Maximum_price  
0      90               0      380.0       16.0         2576.0           3340  
1      87               0      393.0       16.0         1202.0           1955  
2      55               0      493.0        9.0         7175.0          15715  
3      86               0      303.0       16.0         5404.0          13078  
4      27               0      567.0       16.0         4069.0           6244

In [66]:
test2=test1.iloc[:,:].values
test2=x_scaler.fit_transform(test2)

In [67]:
#test1.isnull().sum()
test2

array([[0.7755102 , 0.43524416, 0.        , ..., 0.9375    , 0.14374487,
        0.11431758],
       [0.97959184, 0.00636943, 1.        , ..., 0.9375    , 0.06319615,
        0.06448131],
       [0.        , 0.38853503, 0.        , ..., 0.5       , 0.41335444,
        0.55960563],
       ...,
       [0.26530612, 0.22505308, 1.        , ..., 1.        , 0.03435338,
        0.3861322 ],
       [0.        , 0.22080679, 1.        , ..., 0.875     , 0.07931762,
        0.17998633],
       [0.04081633, 0.35031847, 0.        , ..., 0.5       , 0.31738774,
        0.26422223]])

In [68]:
y_pred=ran_reg.predict(test2)
y_pred1=svr_reg.predict(test2)

In [69]:
y_pred=y_pred.reshape(len(y_pred),1)
y_pred1=y_pred1.reshape(len(y_pred1),1)

In [70]:
y_predicted=y_scaler.inverse_transform(y_pred)
y_predicted1=y_scaler.inverse_transform(y_pred1)

In [71]:
test["Selling_Price"]=y_predicted
y_predicted

array([[ 5111.70216378],
       [ 2954.68474984],
       [16246.3093187 ],
       ...,
       [13189.9592796 ],
       [ 6642.40336148],
       [ 1728.14836164]])

In [72]:
testsvr["Selling_Price"]=y_predicted1
y_predicted1

array([[ 5535.08535886],
       [ 4559.87241935],
       [12694.15982858],
       ...,
       [ 8569.17876738],
       [ 6766.89243424],
       [ 3587.49086179]])

In [73]:
test.to_csv("C:\\Users\\Welcome\\Desktop\\carnival_hackerearth_ml_contest\\submission.csv",columns=["Product_id","Selling_Price"])

In [74]:
testsvr.to_csv("C:\\Users\\Welcome\\Desktop\\carnival_hackerearth_ml_contest\\submission1.csv",columns=["Product_id","Selling_Price"])