In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()

In [6]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [7]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df,iris.target,test_size=0.3)

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), df,iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [12]:
cross_val_score(SVC(gamma='auto'), df,iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [13]:
cross_val_score(RandomForestClassifier(n_estimators=40),df,iris.target,cv=3)

array([0.98, 0.94, 0.94])